version: '3.5'

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

#volumes:
#  memcached:
#    driver: ${VOLUMES_DRIVER}
#  redis:
#    driver: ${VOLUMES_DRIVER}

services:
  workspace:
    build:
      context: ${APP_DOCKER_BUILD_PATH}
      dockerfile: ${APP_DOCKER_BUILD_DOCKERFILE}
      # docker-compose build --build-arg APP_ENV=development
      args:
        - APP_ENV=${APP_BUILD_ARGS_APP_ENV}
        - FLAG_DEVELOP=${APP_BUILD_ARGS_FLAG_DEVELOP}
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    ports:
      - "127.0.0.1:${PROJECT_HOST_PORT}:80"
    # see docker-compose.mount.yml
#    volumes:
#      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
    env_file: 'web-variables.env'
    networks:
      - frontend
      - backend
#  memcached:
#    image: "memcached:latest"
##    volumes:
##      - ${DATA_PATH_HOST}/memcached:/var/lib/memcached
#    networks:
#      - backend
#    ports:
#      - "11211:11211"
#    command: ["memcached"]
  redis:
    image: "redis:latest"
#    volumes:
#      - ${DATA_PATH_HOST}/redis:/data
    networks:
      - backend
    ports:
      - "6379:6379"
    command: ["redis-server"]
